- name: "Install ranger application"
  ansible.builtin.include_tasks: install/main.yml

- name: "Export ranger commands for use with external roles"
  ansible.builtin.include_tasks: export_cmds/main.yml

- name: "Create ranger config dir"
  ansible.builtin.include_tasks: create_config_dir/main.yml

- name: "Add custom ranger python functions in 'commands.py'"
  ansible.builtin.include_tasks: config_commands_py/main.yml

- name: "Add custom ranger scripts"
  ansible.builtin.include_tasks: config_scripts/main.yml

- name: "Set main configurations settings in 'rc.conf'"
  ansible.builtin.include_tasks: config_rc_conf/main.yml

- name: "Set program-selection to open specific file types in 'rifle.conf'"
  ansible.builtin.include_tasks: config_rifle_conf/main.yml

- name: "Set program-selection to preview specific file types in 'scope.sh'"
  ansible.builtin.include_tasks: config_scope_sh/main.yml

