- name: "Configure 'preview_with' programs for user '{{ ranger_user_name }}' in '{{ scope_sh_path }}'"
  ansible.builtin.template:
    dest: "{{ scope_sh_path }}"
    src: "scope_sh.j2"
    owner: "{{ ranger_user_name }}"
    mode: '755'
    force: yes
  vars:
    scope_sh_path: "{{ ranger_user_config_dir }}/scope.sh"
  become: true
  become_user: root

