- name: "Create ranger config dir for user '{{ ranger_user_name }}' at '{{ ranger_user_config_dir }}'"
  ansible.builtin.file:
    path: "{{ ranger_user_config_dir }}"
    state: directory
    owner: "{{ ranger_user_name }}"
    mode: '755'
  become: true
  become_user: root

