- name: "Configure settings for user '{{ ranger_user_name }}' in '{{ rc_conf_path }}'"
  ansible.builtin.template:
    dest: "{{ rc_conf_path }}"
    src: "rc_conf.j2"
    owner: "{{ ranger_user_name }}"
    mode: '644'
    force: yes
  vars:
    rc_conf_path: "{{ ranger_user_config_dir }}/rc.conf"
  become: true
  become_user: root

