- name: "Configure 'open_with' programs for user '{{ ranger_user_name }}' in '{{ rifle_conf_path }}'"
  ansible.builtin.template:
    dest: "{{ rifle_conf_path }}"
    src: "rifle_conf.j2"
    owner: "{{ ranger_user_name }}"
    mode: '644'
    force: true
  vars:
    rifle_conf_path: "{{ ranger_user_config_dir }}/rifle.conf"
  become: true
  become_user: root

