- name: "Create ranger config scripts dir for user '{{ ranger_user_name }}' at '{{ ranger_user_config_scripts_dir }}'"
  ansible.builtin.file:
    path: "{{ ranger_user_config_scripts_dir }}"
    state: directory
    owner: "{{ ranger_user_name }}"
    mode: '755'
  become: true
  become_user: root

- name: "Create custom ranger-in-last-dir scripts for user '{{ ranger_user_name }}' in '{{ ranger_in_last_dir_cmd }}'"
  ansible.builtin.template:
    dest: "{{ ranger_in_last_dir_cmd }}"
    src: "ranger_in_last_dir_sh.j2"
    owner: "{{ ranger_user_name }}"
    mode: '755'
    force: yes
  become: true
  become_user: root

